services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "80:80"
    volumes:
      - mqa_data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
      - API_BASE_URL=http://api:80
    env_file:
      - .env
    depends_on:
      - api
    restart: unless-stopped

volumes:
  mqa_data:
    driver: local