services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      api:
        condition: service_healthy
      frontend:
        condition: service_started
    ports:
      - "0.0.0.0:${NGINX_PORT_HOST:-80}:80"
      - "0.0.0.0:${NGINX_SSLPORT_HOST:-443}:443"
    restart: on-failure:3

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    volumes:
      - mqa_data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - API_BACKEND_PORT=${API_BACKEND_PORT:-5000}
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${API_BACKEND_PORT:-5000}/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    environment:
      - PYTHONUNBUFFERED=1
      # The frontend communicates with the API through NGINX
      - API_BASE_URL=${API_BASE_URL:-http://${PROXY_SERVER_NAME}/api}
      - MQA_FRONTEND_PORT=${MQA_FRONTEND_PORT:-8501}
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mqa_data:
    driver: local